name: CI

on:
  push:

permissions: {}

jobs:
  build:
    uses: thepwagner-org/actions/.github/workflows/golang-test.yaml@05de59550ccea9b58da28fd918fc5a0573328639 # v2.10.0
    permissions:
      contents: read
