name: CI

on:
  push:

permissions: {}

jobs:
  build:
    uses: thepwagner-org/actions/.github/workflows/golang-test.yaml@21218e61b841c17ddd74dace7413b3c73a854592 # v2.8.0
    permissions:
      contents: read
