name: CI

on:
  push:

permissions: {}

jobs:
  build:
    uses: thepwagner-org/actions/.github/workflows/ci-golang.yaml@0e6e8ce011a25c89ec44457b1fddaf9fd34a525f # v2.6.0
    permissions:
      contents: read
