name: CI

on:
  push:

permissions: {}

jobs:
  build:
    uses: thepwagner-org/actions/.github/workflows/golang-test.yaml@29fc277227ae3fc735e9ac7790d307f0516a70c3 # v3.0.0
    permissions:
      contents: read
