name: CI

on:
  push:

permissions: {}

jobs:
  build:
    uses: thepwagner-org/actions/.github/workflows/golang-test.yaml@7a8c48d526143c8b058cd97476f7fcea16deb674 # v2.9.0
    permissions:
      contents: read
