name: CI

on:
  push:

permissions: {}

jobs:
  build:
    uses: thepwagner-org/actions/.github/workflows/ci-golang.yaml@6986c6f842819b20013a705ee6a97a9d6143b289 # v2.5.0
    permissions:
      contents: read
